CGE-133 Create entities for chat implementation
Jack11M/EVO-Exchange-BE-2019 pull request #127
Opened 2020-10-29 14:20 UTC by drw85

Created new models to give possibility of implementing chat. 
New logic covered with integration tests.

2020-11-05 11:53 UTC, Jack11M reviewed
Lots of work!
Please, reply to my comments.

Also when I run all tests, the updateAdvertisement_shouldUpdateExistedAdvertisement() in AdvertisementControllerIntegrationTest fails (please, check it, maybe this is only my problem).

Error message:  junit.framework.ComparisonFailure: row count (table=IMAGE) expected:<[1]> but was:<[2]>

2020-11-05 11:53 UTC, Jack11M commented on src/main/java/com/hillel/items_exchange/model/Message.java
> +    private LocalDateTime updated;
Why don't you extend BaseEntity and use fields: id, created, updated from it?

2020-11-05 11:53 UTC, Jack11M commented on src/main/java/com/hillel/items_exchange/model/Chat.java
> +}
GitHub requires a blank line at the end of each file.

2020-11-05 11:53 UTC, Jack11M commented on src/main/java/com/hillel/items_exchange/model/Message.java
> +        status = MessageStatus.NEW;
Great approach!

2020-11-05 11:53 UTC, Jack11M commented on src/main/java/com/hillel/items_exchange/model/Message.java
> +}
GitHub requires a blank line at the end of each file.

2020-11-05 11:53 UTC, Jack11M commented on src/main/resources/application.properties
> +#logging.file.path=${logs-path}
GitHub requires a blank line at the end of each file.

2020-11-05 11:53 UTC, Jack11M commented on src/test/java/com/hillel/items_exchange/chat/ChatEntitiesIntegrationTest.java
> +public class ChatEntitiesIntegrationTest {
The public modifier is redundant here

2020-11-05 11:53 UTC, Jack11M commented on src/test/java/com/hillel/items_exchange/chat/ChatEntitiesIntegrationTest.java
> +    public void shouldAddNewChatToUser() {
The public modifier is redundant here

2020-11-05 11:53 UTC, Jack11M commented on src/test/java/com/hillel/items_exchange/chat/ChatEntitiesIntegrationTest.java
> +    public void shouldAddAnotherUserToChat() {
The public modifier is redundant here

2020-11-05 11:53 UTC, Jack11M commented on src/test/java/com/hillel/items_exchange/chat/ChatEntitiesIntegrationTest.java
> +    public void shouldAddNewMessageWithNoAttachmentsToUsersChat() {
The public modifier is redundant here

2020-11-05 11:53 UTC, Jack11M commented on src/test/java/com/hillel/items_exchange/chat/ChatEntitiesIntegrationTest.java
> +    public void shouldAddNewMessageWithTwoAttachmentsForAllUsersOfChat() {
The public modifier is redundant here

2020-11-05 11:53 UTC, Jack11M commented on src/test/java/com/hillel/items_exchange/chat/ChatEntitiesIntegrationTest.java
> +    public void shouldRemoveUserWithAllOfHisChatsAndMessagesWithAttachments() {
The public modifier is redundant here

2020-11-05 11:53 UTC, Jack11M commented on src/test/java/com/hillel/items_exchange/chat/ChatEntitiesIntegrationTest.java
> +    public void shouldRemoveUserWithHisMessagesAndAttachmentsForThemButLeaveChat() {
The public modifier is redundant here

2020-11-05 11:53 UTC, Jack11M commented on src/test/java/com/hillel/items_exchange/chat/ChatEntitiesIntegrationTest.java
> +    public void shouldAddUserToBlacklist() {
The public modifier is redundant here

2020-11-05 11:53 UTC, Jack11M commented on src/test/resources/datasets/chat/add_user_to_existing_chat.yml
> +    CHAT_ID: 1
GitHub requires a blank line at the end of each file.

2020-11-05 11:53 UTC, Jack11M commented on src/test/resources/datasets/chat/add_user_to_blacklist.yml
> +    BLOCKED_ID: 2
GitHub requires a blank line at the end of each file.

2020-11-05 11:53 UTC, Jack11M commented on src/test/resources/datasets/chat/add_new_message_without_attachments_to_chat.yml
> +    UPDATED: "2020-10-29 14:02:58.504797"
GitHub requires a blank line at the end of each file.

2020-11-05 11:53 UTC, Jack11M commented on src/test/resources/datasets/chat/add_new_chat_to_user.yml
> +    CHAT_ID: 1
GitHub requires a blank line at the end of each file.

2020-11-05 11:53 UTC, Jack11M commented on src/test/resources/datasets/chat/add_new_attachment_to_message.yml
> +    FILE_CONTENT: "ZmlsZV9jb250ZW50Mg=="
GitHub requires a blank line at the end of each file.

2020-11-05 11:53 UTC, Jack11M commented on src/test/resources/datasets/chat/add_message_with_attachments_for_every_user_in_chat.yml
> +    FILE_CONTENT: "ZGVm"
GitHub requires a blank line at the end of each file.

2020-11-05 11:53 UTC, Jack11M commented on src/test/java/com/hillel/items_exchange/chat/ChatEntitiesIntegrationTest.java
> +}
GitHub requires a blank line at the end of each file.

2020-11-05 11:53 UTC, Jack11M commented on src/test/java/com/hillel/items_exchange/chat/ChatEntitiesIntegrationTest.java
> +
As far as I know, using helper methods in Test classes is bad practice, you can port them to TestUtil instead.

2020-11-06 13:00 UTC, rpkyrych requested changes
Nice job but few things needs to be updated.

2020-11-17 23:43 UTC, lubchik-14 requested changes
So, it's a super job, but I left some comments. 
I also have failed tests AdvertisementControllerIntegrationTest.updateAdvertisement_shouldUpdateExistedAdvertisement somehow.

2020-11-17 23:43 UTC, lubchik-14 commented on src/main/java/com/hillel/items_exchange/model/User.java
> +    @ManyToMany(cascade = {CascadeType.ALL})
I am confused about behavior that we can observe deleting a user. CascadeType.ALL propagates deleting child entity this behavior is not every needed us. Maybe should not use this type here?

2020-11-18 08:17 UTC, closed without merging