CGE-129: Add authorization filter for user/child and user/my-info endpoints
Jack11M/EVO-Exchange-BE-2019 pull request #128
Opened 2020-11-11 18:53 UTC by KozminAlexandr

Add authorization filter for GET method to user/child and user/my-info endpoints. Now for unathorizated user returns 401 error code.
Fix Swagger-UI authorization

2020-11-11 20:22 UTC, rpkyrych approved these changes
Looks good!

2020-11-11 21:55 UTC, Jack11M approved these changes

2020-11-12 09:47 UTC, lubchik-14 requested changes
Ok, if you piked this way out, I would asked you to remove `@PreAuthorize(HAS_ROLE_USER)` above `public ResponseEntity<UserDto> getPersonalInfo(Principal principal)` because it's redundant and doesn't give an opportunity to get info if user has role admin

2020-11-17 16:25 UTC, lubchik-14 approved these changes
👍

2020-11-19 09:50 UTC, svyatoslav145 approved these changes

2020-11-19 20:09 UTC, merged