[CGE-150] Added Ukrainian message responses, removed non-used messages
Jack11M/EVO-Exchange-BE-2019 pull request #182
Opened 2021-03-29 12:49 UTC by rpkyrych

2021-03-29 18:32 UTC, drw85 approved these changes

2021-03-29 19:01 UTC, Jack11M requested changes

2021-03-29 19:01 UTC, Jack11M commented on src/main/resources/messages_ua.properties
> +token.signature.not.valid=Підпис JWT токену не співпадає вирахованій. JWT токен може бути хибним та не містить довіри
It seems like something wrong with this message. You could use "вирахованому"

2021-03-30 09:20 UTC, rpkyrych commented on src/main/java/com/hillel/items_exchange/model/enums/I18n.java
> -    }
I just used this enum into the tests to check localization and made small refactoring. It doesn't related to scope of the task and I could revert changes if you insist.

2021-03-31 20:03 UTC, Jack11M commented on src/main/java/com/hillel/items_exchange/model/enums/I18n.java
> -    }
Could you please revert the changes, because they might affect the logic in my ticket? 
If not, I add these changes in the scope of my ticket.

2021-03-31 20:03 UTC, Jack11M approved these changes

2021-04-01 18:36 UTC, merged