OBMIN-83 Add constraints to prevent new locations creation when they …
Jack11M/EVO-Exchange-BE-2019 pull request #456
Opened 2023-01-30 14:46 UTC by ennnbaev

…already exist

2023-01-30 15:54 UTC, ImAndVlad approved these changes

2023-01-30 18:18 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/model/Location.java
> +@Table(name = "location",
parameter "name" could be omitted because it's became mandatory only when the table and the entity have different names.

2023-01-30 18:18 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/model/Location.java
> +                        "area_en","district_en","city_en"})
Would you mind apply formatting and align it to a single code line?

2023-01-30 18:18 UTC, rpkyrych commented on src/main/resources/liquibase/db.changelog-1.2.xml
> +    <changeSet id="1.2.0: Add unique constraint in table location" author="ennnbaev">
Could you add a new line above?

2023-01-30 18:18 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/end2end/LocationFlowTest.java
> +    @WithMockUser(username = "admin", roles = { "ADMIN" })
You can omit brackets to "roles" parameter because of single value inside.

2023-01-30 18:18 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/end2end/LocationFlowTest.java
> +    @WithMockUser(username = "admin", roles = { "ADMIN" })
Please add an extra space after each of the new test cases. All the methods should have a distance between.

2023-01-30 18:18 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/end2end/LocationFlowTest.java
> +    @WithMockUser(username = "admin", roles = { "ADMIN" })
Single "roles" - no brackets

2023-01-30 18:18 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/end2end/LocationFlowTest.java
> +    void createTwoSameLocation_shouldGetMessageBadRequest() throws Exception
Valid test class name syntax in our case "testMethod_should..._when". I'd be very grateful if you rename all your created test methods according to it.

2023-01-30 18:18 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/end2end/LocationFlowTest.java
> +        sendDtoAndGetResultAction(post(LOCATION), createValidLocationDto(), status().isBadRequest());
By making 2 requests you increase the time of the unit test. Why don't you create a new initial dataset for the test with a new location you used here and just try to recreate it with the second request?

2023-01-30 18:18 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/end2end/LocationFlowTest.java
> +        sendDtoAndGetResultAction(post(LOCATION), createValidLocationDto(), status().isBadRequest());
It would be a much better to use some custom dataset instead of 2 requests.

2023-01-30 18:18 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/end2end/LocationFlowTest.java
> +        sendDtoAndGetResultAction(post(LOCATION), createValidLocationDto(), status().isBadRequest());
It would be much better to use a new custom dataset instead of making 2 requests in a test.

2023-01-30 18:19 UTC, rpkyrych requested changes

2023-01-30 18:19 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/end2end/LocationFlowTest.java
> +        sendAndCompareLocationResponse(post(LOCATION), status().isCreated());
It would be much better to use some custom dataset instead of 2 requests.

2023-01-31 20:49 UTC, rpkyrych approved these changes
Looks awesome!

2023-02-01 18:25 UTC, merged