OBMIN-221 User-avatar-should-be-immposible-to-add-several-photos
Jack11M/EVO-Exchange-BE-2019 pull request #465
Opened 2023-02-06 21:08 UTC by IllyaZuew

2023-02-06 21:38 UTC, ennnbaev approved these changes
Good idea!

2023-02-06 21:49 UTC, rpkyrych requested changes

2023-02-06 21:49 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/controller/UserControllerSeveralAvatarsTest.java
> +    void setUserAvatar_whenReceivedSeveralImages_shouldSaveFirstImage() throws Exception {
That test should be moved to **UserControllerIntegrationTest** because of its type.

2023-02-06 21:49 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/controller/UserControllerSeveralAvatarsTest.java
> +        user = createUser();
That is useless behavior. You have only a single test here so that should be a part of it.

2023-02-06 21:49 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/controller/UserControllerSeveralAvatarsTest.java
> +    @WithMockUser(username = "admin")
Why do you need the admin's preferences here?

2023-02-06 21:49 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/controller/UserControllerSeveralAvatarsTest.java
> +        ArgumentCaptor<MultipartFile> captor = ArgumentCaptor.forClass(MultipartFile.class);
Can be created with the annotation on a test classes level

2023-02-06 21:49 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/controller/UserControllerSeveralAvatarsTest.java
> +        Mockito.verify(imageService).compress(captor.capture());
You should verify the behavior of all mocks and because of that **userService** invoking also has to be verified.

2023-02-06 21:49 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/controller/UserControllerSeveralAvatarsTest.java
> +    private User createUser() {
You don't need to do that because you have used **WithMockUser** annotation.

2023-02-07 11:02 UTC, rpkyrych reviewed
Good, but still needs to be polished.

2023-02-07 11:02 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/controller/UserControllerIntegrationTest.java
> +        Mockito.verify(userService, times(1)).findByUsernameOrEmail(any());
When you apply **verify** by default it would be provided with **times(1)** inside.

2023-02-07 11:02 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/controller/UserControllerIntegrationTest.java
> +        assertEquals(jpeg.getName(), actualImage.getName());
The **compress** method is mocked so you can compare files completely other doing that for their names.

2023-02-07 14:51 UTC, rpkyrych approved these changes

2023-02-07 14:55 UTC, merged