Obmin 240 user is not able to access the functions after account recovery
Jack11M/EVO-Exchange-BE-2019 pull request #478
Opened 2023-02-15 22:09 UTC by Sershok

2023-02-16 05:49 UTC, IllyaZuew commented on src/main/java/space/obminyashka/items_exchange/service/impl/UserServiceImpl.java
> +        roleService.getRole(savedUsersRole.get(user.getUsername())).ifPresent(user::setRole);
I think You should set only role ROLE_USER without using map for activating account, but you should check that user has role ROLE_SELF_REMOVING and after that if it is true, activate account by changing role to USER_ROLE

2023-02-16 05:51 UTC, IllyaZuew commented on src/main/java/space/obminyashka/items_exchange/service/impl/UserServiceImpl.java
> +        roleService.getRole(savedUsersRole.get(user.getUsername())).ifPresent(user::setRole);
or using @PreAuthorize on method in controller for checking role

2023-02-16 11:06 UTC, IllyaZuew approved these changes

2023-02-16 11:16 UTC, ennnbaev approved these changes
Looks good

2023-02-18 09:48 UTC, rpkyrych requested changes

2023-02-18 09:48 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/dao/RoleRepository.java
> +    void updateUserRole(String userName);
1. The method's name doesn't fit its behavior. I propose to rename it to **setUserRoleToUserByUsername**
2. "username" is the word in lowercase

2023-02-18 09:48 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/service/RoleService.java
> +    public void updateUserRole(String username) {
The name of the method doesn't correspond to its behavior. For the current name, it should be the second parameter **role** in it.

2023-02-18 09:48 UTC, rpkyrych commented on src/main/java/space/obminyashka/items_exchange/service/impl/UserServiceImpl.java
>          userRepository.saveAndFlush(user);
Here are a couple of comments on the whole method:
1. You don't need to save and flush the user when you update him in **updateUserRole** method.
2. You have to pass fewer privileges to the method. If you need only a username here pass only it, no need to pass the whole user.

2023-02-18 09:48 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/end2end/UserFlowTest.java
> +            ignoreCols = {"password", "lastOnlineTime", "updated","status"})
formatting

2023-02-18 09:48 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/service/UserServiceIntegrationTest.java
> +
Why do we need to merge empty spaces from the test?

2023-02-18 09:48 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/service/UserServiceIntegrationTest.java
> -    void makeAccountActiveAgain_WhenDataCorrect_Successfully() {
All the test cases have to be created according to the [test pyramid](https://martinfowler.com/articles/practical-test-pyramid.html).
That means that the same logic has to be covered with the unit, integration, end 2 end tests.
You shouldn't remove the test when you have an end 2 end test for the same part of the code but update that integration test as well.
Each test has its own purpose: end 2 end - check the whole flow; integration - work with Spring context and beans; unit - no Spring context and describes only single behavior of a tested method.

2023-02-22 13:40 UTC, rpkyrych requested changes

2023-02-22 13:40 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/service/UserServiceIntegrationTest.java
> +    void makeAccountActiveAgain_WhenDataCorrect_Successfully() {
The test isn't valid at all.

1. You set the new username
2. You set "ROLE_USER"
3. You invoke the tested method
4. You validate that the user has the "ROLE_USER" but you did that in step 2.

How the tested method's result is compared?

2023-02-22 13:40 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/service/UserServiceIntegrationTest.java
> -    void makeAccountActiveAgain_WhenDataCorrect_Successfully() {
Could you please update it here rather than move it up?

2023-02-22 16:46 UTC, rpkyrych commented on src/test/java/space/obminyashka/items_exchange/end2end/UserFlowTest.java
>          UserDeleteFlowDto userDeleteFlowDto = new UserDeleteFlowDto(CORRECT_OLD_PASSWORD, CORRECT_OLD_PASSWORD);
```suggestion
        var userDeleteFlowDto = new UserDeleteFlowDto(CORRECT_OLD_PASSWORD, CORRECT_OLD_PASSWORD);
```

2023-02-23 16:23 UTC, rpkyrych approved these changes

2023-02-23 18:01 UTC, IllyaZuew approved these changes

2023-02-23 21:14 UTC, merged